### ISSUE TITLE
Mention component is obsolete in current Antd version

### ISSUE THREAD

**Issue by gonozalviii** [samgarasx/kotlin-js-wrappers#2] opened 2020-04-14 19:13 UTC
The wrapper still references the Mention component, which is not  in the current Antd version anymore.

```
ERROR in ./kotlin-dce/kotlin-js-wrappers-kotlin-antd.js
  Module not found: Error: Can't resolve 'antd/lib/mention'
```

**Comment by oxiadenine** [comment] 2020-04-18 18:55
Duplicate of #1.

**Closed as completed** 2020-09-11 21:31 UTC
